# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "MODO"
description:        "a clean, lightweight and minimalistic blog theme for jekyll"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
#url:                "http://aweekj.github.io"

author:             "Modo"
twitter:
  username:         "__modo_"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain

# Image path in the posts
image:              /static/img/posts

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Tags"
    url:            #"/tags/index.html"
  - name:           "TIL"
    url:            "https://github.com/AWEEKJ/TIL"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag

exclude:            [vendor]
